services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw  
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data 
  mongodb:
    image: mongo
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
     - 27017:27017
    volumes:
      - /var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  auction-svc:
    image: shehabmohamed/auction-svc:latest
    build: 
      context: .
      dockerfile: src/AuctionService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=Auctions;User Id=postgres;Password=postgrespw
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq


  search-svc:
    image: shehabmohamed/search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq

  gateway-svc:
    image: shehabmohamed/gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GatwayService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
   
  identity-svc:
    image: shehabmohamed/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=Identity;User Id=postgres;Password=postgrespw
    ports:
      - 5000:80
    depends_on:
      - postgres
