
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw  # Corrected environment variable
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Correct volume path

volumes:
  pgdata: {}