
# Use .NET SDK for building
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
EXPOSE 80

# Copy solution and project files
COPY Carsties.sln Carsties.sln
COPY src/AuctionService/AuctionService.csproj src/AuctionService/AuctionService.csproj
COPY src/SearchService/SearchService.csproj src/SearchService/SearchService.csproj
COPY src/GatwayService/GatwayService.csproj src/GatwayService/GatwayService.csproj
COPY src/IdentityService/IdentityService.csproj src/IdentityService/IdentityService.csproj
COPY src/Contracts/Contracts.csproj src/Contracts/Contracts.csproj

# Restore packages
RUN dotnet restore Carsties.sln

# Copy the entire app
COPY src/GatwayService src/GatwayService
# Build the AuctionService
WORKDIR /app/src/GatwayService
RUN dotnet publish -c Release -o /app/src/out

# Use ASP.NET runtime for production
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/src/out ./
ENTRYPOINT ["dotnet", "GatwayService.dll"]
